/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMentoriasRouteImport } from './routes/_authenticated/mentorias'
import { Route as AuthenticatedFerramentasRouteImport } from './routes/_authenticated/ferramentas'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCaptacaoRouteImport } from './routes/_authenticated/captacao'
import { Route as AuthenticatedAprendizadoRouteImport } from './routes/_authenticated/aprendizado'
import { Route as AuthenticatedFerramentasPlanejamentoRouteImport } from './routes/_authenticated/ferramentas.planejamento'
import { Route as AuthenticatedFerramentasPitchDeckRouteImport } from './routes/_authenticated/ferramentas.pitch-deck'
import { Route as AuthenticatedFerramentasKanbanRouteImport } from './routes/_authenticated/ferramentas.kanban'
import { Route as AuthenticatedFerramentasCalculadoraRouteImport } from './routes/_authenticated/ferramentas.calculadora'
import { Route as AuthenticatedFerramentasAgendaRouteImport } from './routes/_authenticated/ferramentas.agenda'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMentoriasRoute = AuthenticatedMentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFerramentasRoute =
  AuthenticatedFerramentasRouteImport.update({
    id: '/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaptacaoRoute = AuthenticatedCaptacaoRouteImport.update({
  id: '/captacao',
  path: '/captacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAprendizadoRoute =
  AuthenticatedAprendizadoRouteImport.update({
    id: '/aprendizado',
    path: '/aprendizado',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFerramentasPlanejamentoRoute =
  AuthenticatedFerramentasPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedFerramentasRoute,
  } as any)
const AuthenticatedFerramentasPitchDeckRoute =
  AuthenticatedFerramentasPitchDeckRouteImport.update({
    id: '/pitch-deck',
    path: '/pitch-deck',
    getParentRoute: () => AuthenticatedFerramentasRoute,
  } as any)
const AuthenticatedFerramentasKanbanRoute =
  AuthenticatedFerramentasKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => AuthenticatedFerramentasRoute,
  } as any)
const AuthenticatedFerramentasCalculadoraRoute =
  AuthenticatedFerramentasCalculadoraRouteImport.update({
    id: '/calculadora',
    path: '/calculadora',
    getParentRoute: () => AuthenticatedFerramentasRoute,
  } as any)
const AuthenticatedFerramentasAgendaRoute =
  AuthenticatedFerramentasAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedFerramentasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/aprendizado': typeof AuthenticatedAprendizadoRoute
  '/captacao': typeof AuthenticatedCaptacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/ferramentas': typeof AuthenticatedFerramentasRouteWithChildren
  '/mentorias': typeof AuthenticatedMentoriasRoute
  '/ferramentas/agenda': typeof AuthenticatedFerramentasAgendaRoute
  '/ferramentas/calculadora': typeof AuthenticatedFerramentasCalculadoraRoute
  '/ferramentas/kanban': typeof AuthenticatedFerramentasKanbanRoute
  '/ferramentas/pitch-deck': typeof AuthenticatedFerramentasPitchDeckRoute
  '/ferramentas/planejamento': typeof AuthenticatedFerramentasPlanejamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/aprendizado': typeof AuthenticatedAprendizadoRoute
  '/captacao': typeof AuthenticatedCaptacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/ferramentas': typeof AuthenticatedFerramentasRouteWithChildren
  '/mentorias': typeof AuthenticatedMentoriasRoute
  '/ferramentas/agenda': typeof AuthenticatedFerramentasAgendaRoute
  '/ferramentas/calculadora': typeof AuthenticatedFerramentasCalculadoraRoute
  '/ferramentas/kanban': typeof AuthenticatedFerramentasKanbanRoute
  '/ferramentas/pitch-deck': typeof AuthenticatedFerramentasPitchDeckRoute
  '/ferramentas/planejamento': typeof AuthenticatedFerramentasPlanejamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/aprendizado': typeof AuthenticatedAprendizadoRoute
  '/_authenticated/captacao': typeof AuthenticatedCaptacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/ferramentas': typeof AuthenticatedFerramentasRouteWithChildren
  '/_authenticated/mentorias': typeof AuthenticatedMentoriasRoute
  '/_authenticated/ferramentas/agenda': typeof AuthenticatedFerramentasAgendaRoute
  '/_authenticated/ferramentas/calculadora': typeof AuthenticatedFerramentasCalculadoraRoute
  '/_authenticated/ferramentas/kanban': typeof AuthenticatedFerramentasKanbanRoute
  '/_authenticated/ferramentas/pitch-deck': typeof AuthenticatedFerramentasPitchDeckRoute
  '/_authenticated/ferramentas/planejamento': typeof AuthenticatedFerramentasPlanejamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/aprendizado'
    | '/captacao'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/ferramentas'
    | '/mentorias'
    | '/ferramentas/agenda'
    | '/ferramentas/calculadora'
    | '/ferramentas/kanban'
    | '/ferramentas/pitch-deck'
    | '/ferramentas/planejamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/aprendizado'
    | '/captacao'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/ferramentas'
    | '/mentorias'
    | '/ferramentas/agenda'
    | '/ferramentas/calculadora'
    | '/ferramentas/kanban'
    | '/ferramentas/pitch-deck'
    | '/ferramentas/planejamento'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/aprendizado'
    | '/_authenticated/captacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/empresa'
    | '/_authenticated/ferramentas'
    | '/_authenticated/mentorias'
    | '/_authenticated/ferramentas/agenda'
    | '/_authenticated/ferramentas/calculadora'
    | '/_authenticated/ferramentas/kanban'
    | '/_authenticated/ferramentas/pitch-deck'
    | '/_authenticated/ferramentas/planejamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mentorias': {
      id: '/_authenticated/mentorias'
      path: '/mentorias'
      fullPath: '/mentorias'
      preLoaderRoute: typeof AuthenticatedMentoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ferramentas': {
      id: '/_authenticated/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AuthenticatedFerramentasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/captacao': {
      id: '/_authenticated/captacao'
      path: '/captacao'
      fullPath: '/captacao'
      preLoaderRoute: typeof AuthenticatedCaptacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aprendizado': {
      id: '/_authenticated/aprendizado'
      path: '/aprendizado'
      fullPath: '/aprendizado'
      preLoaderRoute: typeof AuthenticatedAprendizadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ferramentas/planejamento': {
      id: '/_authenticated/ferramentas/planejamento'
      path: '/planejamento'
      fullPath: '/ferramentas/planejamento'
      preLoaderRoute: typeof AuthenticatedFerramentasPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedFerramentasRoute
    }
    '/_authenticated/ferramentas/pitch-deck': {
      id: '/_authenticated/ferramentas/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/ferramentas/pitch-deck'
      preLoaderRoute: typeof AuthenticatedFerramentasPitchDeckRouteImport
      parentRoute: typeof AuthenticatedFerramentasRoute
    }
    '/_authenticated/ferramentas/kanban': {
      id: '/_authenticated/ferramentas/kanban'
      path: '/kanban'
      fullPath: '/ferramentas/kanban'
      preLoaderRoute: typeof AuthenticatedFerramentasKanbanRouteImport
      parentRoute: typeof AuthenticatedFerramentasRoute
    }
    '/_authenticated/ferramentas/calculadora': {
      id: '/_authenticated/ferramentas/calculadora'
      path: '/calculadora'
      fullPath: '/ferramentas/calculadora'
      preLoaderRoute: typeof AuthenticatedFerramentasCalculadoraRouteImport
      parentRoute: typeof AuthenticatedFerramentasRoute
    }
    '/_authenticated/ferramentas/agenda': {
      id: '/_authenticated/ferramentas/agenda'
      path: '/agenda'
      fullPath: '/ferramentas/agenda'
      preLoaderRoute: typeof AuthenticatedFerramentasAgendaRouteImport
      parentRoute: typeof AuthenticatedFerramentasRoute
    }
  }
}

interface AuthenticatedFerramentasRouteChildren {
  AuthenticatedFerramentasAgendaRoute: typeof AuthenticatedFerramentasAgendaRoute
  AuthenticatedFerramentasCalculadoraRoute: typeof AuthenticatedFerramentasCalculadoraRoute
  AuthenticatedFerramentasKanbanRoute: typeof AuthenticatedFerramentasKanbanRoute
  AuthenticatedFerramentasPitchDeckRoute: typeof AuthenticatedFerramentasPitchDeckRoute
  AuthenticatedFerramentasPlanejamentoRoute: typeof AuthenticatedFerramentasPlanejamentoRoute
}

const AuthenticatedFerramentasRouteChildren: AuthenticatedFerramentasRouteChildren =
  {
    AuthenticatedFerramentasAgendaRoute: AuthenticatedFerramentasAgendaRoute,
    AuthenticatedFerramentasCalculadoraRoute:
      AuthenticatedFerramentasCalculadoraRoute,
    AuthenticatedFerramentasKanbanRoute: AuthenticatedFerramentasKanbanRoute,
    AuthenticatedFerramentasPitchDeckRoute:
      AuthenticatedFerramentasPitchDeckRoute,
    AuthenticatedFerramentasPlanejamentoRoute:
      AuthenticatedFerramentasPlanejamentoRoute,
  }

const AuthenticatedFerramentasRouteWithChildren =
  AuthenticatedFerramentasRoute._addFileChildren(
    AuthenticatedFerramentasRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAprendizadoRoute: typeof AuthenticatedAprendizadoRoute
  AuthenticatedCaptacaoRoute: typeof AuthenticatedCaptacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedFerramentasRoute: typeof AuthenticatedFerramentasRouteWithChildren
  AuthenticatedMentoriasRoute: typeof AuthenticatedMentoriasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAprendizadoRoute: AuthenticatedAprendizadoRoute,
  AuthenticatedCaptacaoRoute: AuthenticatedCaptacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedFerramentasRoute: AuthenticatedFerramentasRouteWithChildren,
  AuthenticatedMentoriasRoute: AuthenticatedMentoriasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
